# Site settings
title: Medical Assistive Robot
tag_text: Medical Assistive Robot
description: Medical Assistive Robot
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
